# Generated by Django 3.0.7 on 2020-06-11 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Grade', '0001_initial'),
        ('Section', '0001_initial'),
        ('Alumns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberInscription', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('nameAlumn', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Alumns.Alumn')),
                ('nameGrade', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Grade.Grade')),
                ('nameSection', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Section.Section')),
            ],
        ),
    ]
