# Generated by Django 3.0.7 on 2020-06-11 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Section', '0001_initial'),
        ('Grade', '0001_initial'),
        ('Inscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='nameGrade',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Grade.Grade'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='nameSection',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Section.Section'),
        ),
    ]
