# Generated by Django 3.0.7 on 2020-06-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnetAlumn', models.CharField(max_length=18)),
                ('nameAlumn', models.CharField(max_length=50)),
                ('surnameAlumn', models.CharField(max_length=50)),
                ('directionAlumn', models.TextField(max_length=75)),
                ('slug', models.SlugField(unique=True)),
                ('imageAlumn', models.ImageField(upload_to='alumns/')),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
